version: '3'

services:
  vault-server:
    image: vault:1.12.0
    container_name: vault-server
    ports:
      - '8200:8200'
    environment:
      VAULT_ADDR: http://localhost:8200
    volumes:
      - ./settings/config.json:/vault/config/config.json
      - vault-data:/vault/file/
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  vault-init:
    image: vault:1.12.0
    container_name: vault-init
    environment:
      VAULT_ADDR: http://vault-server:8200
      MY_VAULT_TOKEN: ${MY_VAULT_TOKEN}
    volumes:
      - ./settings/vault-init.sh:/usr/local/bin/vault-init.sh
      - vault-data:/vault/file/
    command: /usr/local/bin/vault-init.sh
    restart: on-failure
    depends_on:
      - vault-server

volumes:
  vault-data:
